[tool.poetry]
name = "optiface"
version = "0.1.0"
description = ""
authors = ["Peter Sanders <pete.sanders97@gmail.com>", "Luca Wrabetz <wrabetzluca@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.4"
numpy = "^2.2.0"
pandas = "^2.2.3"
pyyaml = "^6.0.2"
pydantic = "^2.10.3"
setuptools = "^75.6.0"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pylint = "^3.3.2"
mypy = "^1.13.0"
pre-commit = "^4.0.1"
types-pyyaml = "^6.0.12.20240917"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.mypy.overrides]
module = ["setuptools.*"]
follow_untyped_imports = true
ignore_missing_imports = true

[tool.pylint.'MASTER']
max-line-length=88

[tool.pylint.'FORMAT']
msg-template = "{line}:{column}: {msg_id}: {msg}"
disable = ["C0114", "C0115", "C0116"]

[tool.pylint.'TYPECHECK']
disable = "all"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"